"""add cost_price and profit_margin to products

Revision ID: 0a0ab1d05d2c
Revises: 
Create Date: 2026-01-22 00:10:25.359412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0ab1d05d2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('profit_margin', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'CANCELLED', name='sale_status'), nullable=False))
    op.add_column('sales', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('amount_remaining', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'MIXED', name='payment_method'), nullable=False))
    op.add_column('sales', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('sales', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'sales', 'sellers', ['seller_id'], ['id'])
    op.drop_column('sales', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'due_date')
    op.drop_column('sales', 'notes')
    op.drop_column('sales', 'payment_method')
    op.drop_column('sales', 'amount_remaining')
    op.drop_column('sales', 'amount_paid')
    op.drop_column('sales', 'discount')
    op.drop_column('sales', 'subtotal')
    op.drop_column('sales', 'status')
    op.drop_column('sales', 'seller_id')
    op.drop_column('products', 'profit_margin')
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
