"""actualizar valor por defecto profit

Revision ID: 65d70909f2c0
Revises: 0a0ab1d05d2c
Create Date: 2026-01-22 00:20:09.483836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d70909f2c0'
down_revision: Union[str, None] = '0a0ab1d05d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
