"""add earnings table

Revision ID: 78d82711b2b5
Revises: 66c61fca8c11
Create Date: 2026-02-01 14:43:32.483135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d82711b2b5'
down_revision: Union[str, None] = '66c61fca8c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('earnings', sa.Column('cost_price', sa.Float(), nullable=False))
    op.add_column('earnings', sa.Column('sale_price', sa.Float(), nullable=False))
    op.add_column('earnings', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('earnings', sa.Column('total_cost', sa.Float(), nullable=False))
    op.add_column('earnings', sa.Column('total_revenue', sa.Float(), nullable=False))
    op.add_column('earnings', sa.Column('profit', sa.Float(), nullable=False))
    op.add_column('earnings', sa.Column('profit_margin', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'earnings', 'products', ['product_id'], ['id'])
    op.drop_column('earnings', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'earnings', type_='foreignkey')
    op.drop_column('earnings', 'profit_margin')
    op.drop_column('earnings', 'profit')
    op.drop_column('earnings', 'total_revenue')
    op.drop_column('earnings', 'total_cost')
    op.drop_column('earnings', 'quantity')
    op.drop_column('earnings', 'sale_price')
    op.drop_column('earnings', 'cost_price')
    op.drop_column('earnings', 'product_id')
    # ### end Alembic commands ###
